### ISSUE TITLE
Pre-process move-original for Azure

### ISSUE THREAD

**Issue by NoelAbrahams** [blitline-dev/blitline_node#7]
Hi,

There appears to be a way to [move the original to an Amazon S3 container](http://www.blitline.com/docs/beta) via the beta `pre-process` feature.

From the example:

``` json
{
    "application_id":"YOUR_APP_ID",
    "src":"http://cdn.blitline.com/filters/boys.jpeg",
    "pre_process":{
        "move_original":{
            "s3_destination":{
                "bucket":"bltemp",
                "key":"grumpy_squirrel/moved_original_foo23.png"
            }
        }
    },
    "functions":[
        {
            "name":"resize_to_fit",
            "params":{
                "width":100
            },
            "save":{
                "image_identifier":"MY_CLIENT_ID"
            }
        }
    ]
}
```

Is there a way to specify a Microsoft Azure blob container instead?

**Comment by blitline-dev** [comment]
Yes. You should be able to use an azure_destination
http://docs.blitline.com/articles/azure_destination.html instead of an
s3_destination.

for example:

{
  "application_id": "YOUR_APP_ID",
  "src": "http://cdn.blitline.com/filters/boys.jpeg",
  "pre_process": {
    "move_original": {
      "azure_destination": {
        "account_name": "YOUR_AZURE_APP",
        "shared_access_signature": "http://<YOUR STORE>.
blob.core.windows.net/sample/image.jpg?sr=b&sv=2012-02-12&st=2013-04-12T03%3A18%3A30Z&se=2013-04-12T04%3A18%3A30Z&sp=w&sig=Bte2hkkbwTT2sqlkkKLop2asByrE0sIfeesOwj7jNA5o%3D
"
      }
    }
  },
  "functions": [
    {
      "name": "resize_to_fit",
      "params": {
        "width": 100
      },
      "save": {
        "image_identifier": "MY_CLIENT_ID"
      }
    }
  ]
}

## 

Blitline Support
Sent with Airmail

On September 1, 2016 at 5:36:11 AM, nabog (notifications@github.com) wrote:

Hi,

There appears to be a way to move the original to an Amazon S3 container
http://www.blitline.com/docs/beta via the beta pre-process feature.

From the example:

{
    "application_id":"YOUR_APP_ID",
    "src":"http://cdn.blitline.com/filters/boys.jpeg",
    "pre_process":{
        "move_original":{
            "s3_destination":{
                "bucket":"bltemp",
                "key":"grumpy_squirrel/moved_original_foo23.png"
            }
        }
    },
    "functions":[
        {
            "name":"resize_to_fit",
            "params":{
                "width":100
            },
            "save":{
                "image_identifier":"MY_CLIENT_ID"
            }
        }
    ]
}

Is there a way to specify a Microsoft Azure blob container instead?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/blitline-dev/blitline_node/issues/7, or mute the thread

**Comment by NoelAbrahams** [comment]
That's great to know, thanks!
